controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: '/{_locale}'
    defaults:
        _locales: '%app.locale%'

home_controller:
    resource: ../src/Controller/HomeController.php
    type: attribute

image_controller:
    resource: ../src/Controller/ImageController.php
    type: attribute